### ISSUE TITLE
container won't start

### ISSUE THREAD

**Issue by IronicBadger** [ninthwalker/NowShowing#29]
I get the following error on first run of the container, double checked permissions in the `appdata` directory I have set.

```
[cont-init.d] 20-setup: executing... 
/usr/local/sbin/config-setup:63:in `setServer': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /usr/local/sbin/config-setup:85:in `start'
	from /usr/local/sbin/config-setup:94:in `<main>'
```
Any common stuff for me to try first?

**Comment by ninthwalker** [comment]
A couple things to check for me.
What did you set for the docker template variable 'PLEX_SERVER_IP'? (example, not real info)
Also, did it write any files to your appdata dir?

**Comment by IronicBadger** [comment]
Here is what i put in my docker compose file i use the manage all my
containers.

```
  nowshowing:
    image: ninthwalker/nowshowing
    container_name: nowshowing
    volumes:
      - /opt/appdata/nowshowing:/config
    ports:
      - 27024:6789
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ="Europe/London"
      - PLEX_USERNAME="abc@gmail.com" \
      - PLEX_PASSWORD="blah" \
      - SMTP_SERVER="smtp.gmail.com" \
      - SMTP_PORT="587" \
      - EMAIL_USERNAME="abc@gmail.com" \
      - EMAIL_PASSWORD="blah" \
    restart: always
```

`PGID` and `PUID` are set the the dockeruser of 1050 same as all the other
containers i run by LSIO. Your container picks this up fine in the logs and
files are populated in the specified `config` directory.
