### ISSUE TITLE
Question: plex_user_emails or not to plex_user_emails?

### ISSUE THREAD

**Issue by ryanborstelmann** [ninthwalker/NowShowing#33]
I think I may be confusing myself here, but my first emailreport ran this morning, and no emails were sent out. I'm starting to wonder how I should have my `advanced.yaml` file set up. Here's what it looks like now:
```
plex:
  plex_user_emails: 'no'
mail:
  from: 'me'
  subject: 'New This Week on Plex!'
  recipients_email: ['']
  recipients: ['myusername', 'username1', 'username2']
```

It was my understanding that by selecting `no` for `plex_user_emails`, I could specify exact users to send to using the `recipients` field, instead of sending to **every** user I'm friends with. Is that the case? When the report ran (and I know it ran because the logs show it collecting things at the proper time), no emails were generated. 

Can I have some guidance on how to set this up? do I need `plex_user_emails` set to `yes`? When I ran the report manually using `docker exec nowshowing emailreport`, it worked as expected, though.

Thanks!

**Comment by ninthwalker** [comment]
Sorry for just now replying.
This is a little quirk that I did not fully explain well enough.
I will update the documentation to explain further.

But to answer your question, specifying `plex_user_emails: 'no'`
Is the correct way to have it NOT automatically send to plex users emails. If that is set to 'no' it will only send to emails or usernames listed in the `recipients_email: and recipients:` fields.

Here is the one catch however that I did not explain well enough. for `plex_user_emails: 'no'` to work, it must have at least one email address in the `recipients_email:` field. It does however always email the server owner, so if you put that same email in the `recipients_email:` field you may get 2 emails to your address. But this will allow you to be able to specify specific usernames to go to as well.

So for an example it would look like the below and it would send an email to my plex friend 'superman', to my personal email 'batman@gmail.com' and then also to my plex server owners email by default.

```
plex:
  plex_user_emails: 'no'
mail:
  from: 'me'
  subject: 'New This Week on Plex!'
  recipients_email: ['batman@gmail.com']
  recipients: ['superman', 'robin']
```
