### ISSUE TITLE
Filtering Users

### ISSUE THREAD

**Issue by dballard8** [ninthwalker/NowShowing#52]
I don't want to send emails out to every single one of my users. Is this possible?

I thought I could change it in advances.yaml by setting:

plex_user_emails: 'no'
recipients: ['user1', 'user2']

But this still sends to everyone.

**Comment by ninthwalker** [comment]
See the wiki. [Advanced Settings](https://github.com/ninthwalker/NowShowing/wiki/Advanced-Settings)

This should work:
```
plex:
  plex_user_emails: 'no'
mail:
  from: 'Plex Server'
  subject: 'Now Showing'
  recipients_email: ['one_email_must_exist_here@gmail.com']
  recipients: ['batman', 'superman', 'joe']
```
