### ISSUE TITLE
Can't create webreport

### ISSUE THREAD

**Issue by 1activegeek** [ninthwalker/NowShowing#58]
I'm attempting to run just the web report. This initially was working. I just noticed the other day when I check on it, that the web report stopped updating on the 30th. I am running the Docker container version and as mentioned had it all working. Now I'm getting the following trying to run the command line manual creation:
```
/usr/lib/ruby/2.3.0/psych.rb:379:in `parse': (/config/advanced.yaml): did not find expected key while parsing a block mapping at line 22 column 3 (Psych::SyntaxError)
	from /usr/lib/ruby/2.3.0/psych.rb:379:in `parse_stream'
	from /usr/lib/ruby/2.3.0/psych.rb:327:in `parse'
	from /usr/lib/ruby/2.3.0/psych.rb:254:in `load'
	from /usr/lib/ruby/2.3.0/psych.rb:475:in `block in load_file'
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /usr/local/sbin/webreport:67:in `initialize'
	from /usr/local/sbin/webreport:370:in `new'
	from /usr/local/sbin/webreport:370:in `main'
	from /usr/local/sbin/webreport:398:in `<main>'
```
This is the content of the file:
```
---
email:
  title: 'New This Week'
  image: 'http://i.imgur.com/LNTSbFl.png'
  footer: 'Thanks for watching!'
  language: 'en'
web:
  title_image: 'img/nowshowing.png'
  logo: 'img/logo.png'
  headline_title: 'Just added:'
  headliners: 'Laughs, Screams, Thrills, Entertainment'
  footer: 'Thanks for watching!'
  language: 'en'
plex:
  plex_user_emails: 'no'
mail:
  from: 'Plex Server'
  subject: 'Now Showing'
  recipients_email: ['']
  recipients: ['']
report:
  interval: 7
  report_type: 'webonly'
  email_report_time: ''
  web_report_time: '30 23 * * *''
  extra_details: 'yes'
  test: 'disable'
```
